Add Authentication screens, Product Detail, Populate User Closet
StephenKodua/Wardrobe pull request #2
Opened 2022-07-08 19:09 UTC by StephenKodua

2022-07-11 21:13 UTC, 3dm1 requested changes

2022-07-11 21:13 UTC, 3dm1 commented on app/src/main/java/com/example/onsalestore/activities/ItemDetailActivity.java
> +                        Toast.makeText(ItemDetailActivity.this, "Successfully Added To Closet", Toast.LENGTH_SHORT).show();
You're showing this toast twice, which doesn't seem right.

I'd suggest to look into Android Snackbars and if they would work here. It could be interesting to navigate to the closet from it.

2022-07-11 21:13 UTC, 3dm1 commented on app/src/main/java/com/example/onsalestore/fragments/ClosetFragment.java
> +        JSONArray itemsInCloset = currentUser.getJSONArray("closet");
The proper way to do this is with a foreign key in the DB.

2022-07-11 21:13 UTC, 3dm1 commented on app/src/main/java/com/example/onsalestore/objects/ClothingItem.java
> +                        itemUrl){
This seems to be oddly formatted.

2022-07-12 05:43 UTC, StephenKodua commented on app/src/main/java/com/example/onsalestore/fragments/ClosetFragment.java
> +        JSONArray itemsInCloset = currentUser.getJSONArray("closet");
Dear Edson, I may be wrong but it looks like Parse does not have foreign keys implementation. I have read the documentation and also searched on the internet for 'parse foreign keys implementation'. What I am getting is basically using a pointer or relationship for foreign key linking or to link to the foreign object objectId.

2022-07-12 21:18 UTC, 3dm1 approved these changes

2022-07-12 21:18 UTC, 3dm1 commented on app/src/main/java/com/example/onsalestore/objects/PostItem.java
> +    public void setItemImageUrl(String postImageUrl) {put(KEY_ITEM_POST_IMAGE, postImageUrl);}
As we discussed, let's store the whole ClosetItem and not just the picture.

2022-07-12 21:18 UTC, merged